//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moneys
    {
        public int id { get; set; }
        public int userid { get; set; }
        public Nullable<int> cash { get; set; }
        public Nullable<int> credit { get; set; }
        public Nullable<int> dayForCredit { get; set; }
    }
}
