//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autoes> Autoes { get; set; }
        public virtual DbSet<Bazaars> Bazaars { get; set; }
        public virtual DbSet<Credits> Credits { get; set; }
        public virtual DbSet<Details> Details { get; set; }
        public virtual DbSet<Moneys> Moneys { get; set; }
        public virtual DbSet<NameOfMashins> NameOfMashins { get; set; }
        public virtual DbSet<TypeMashins> TypeMashins { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<Utilits> Utilits { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
        public virtual DbSet<Zakazs> Zakazs { get; set; }
    }
}
