//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeMashins
    {
        public int id { get; set; }
        public string nameAuto { get; set; }
        public string kyzov { get; set; }
        public Nullable<int> colKyzov { get; set; }
        public string koleso { get; set; }
        public Nullable<int> colKoleso { get; set; }
        public string motor { get; set; }
        public Nullable<int> colMotor { get; set; }
    }
}
