//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workers
    {
        public int id { get; set; }
        public int userId { get; set; }
        public Nullable<int> colWorkers { get; set; }
        public Nullable<int> zp { get; set; }
        public Nullable<int> al { get; set; }
        public Nullable<int> dayOfStrike { get; set; }
        public bool strik { get; set; }
    }
}
