//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakazs
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> col { get; set; }
        public Nullable<int> money { get; set; }
    }
}
